<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Sales Report</title>
    <!-- <link rel="stylesheet" href="style.css" media="all" /> -->
    <style type="text/css">
        .clearfix:after {
  content: "";
  display: table;
  clear: both;
}

a {
  color: #5D6975;
  text-decoration: underline;
}

body {
  position: relative;
  width: 21cm;  
  height: 29.7cm; 
  margin: 0 auto; 
  color: #001028;
  background: #FFFFFF; 
  font-family: Arial, sans-serif; 
  font-size: 12px; 
  font-family: Arial;
}

header {
  padding: 10px 0;
  margin-bottom: 30px;
}

#logo {
  text-align: center;
  margin-bottom: 10px;
}

#logo img {
  width: 90px;
}

h1 {
  border-top: 1px solid  #5D6975;
  border-bottom: 1px solid  #5D6975;
  color: #5D6975;
  font-size: 2.4em;
  line-height: 1.4em;
  font-weight: normal;
  text-align: center;
  margin: 0 0 20px 0;
  background: url(dimension.png);
}

#project {
  float: left;
}

#project span {
  color: #5D6975;
  text-align: right;
  width: 52px;
  margin-right: 10px;
  display: inline-block;
  font-size: 0.8em;
}

#company {
  float: right;
  text-align: right;
}

#project div,
#company div {
  white-space: nowrap;        
}

table {
  width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
  margin-bottom: 20px;
}

table tr:nth-child(2n-1) td {
  background: #F5F5F5;
}

table th,
table td {
  text-align: center;
}

table th {
  padding: 5px 20px;
  color: #5D6975;
  border-bottom: 1px solid #C1CED9;
  white-space: nowrap;        
  font-weight: normal;
}

table .service,
table .desc {
  text-align: left;
}

table td {
  padding: 20px;
  text-align: right;
}

table td.service,
table td.desc {
  vertical-align: top;
}

table td.unit,
table td.qty,
table td.total {
  font-size: 1.2em;
}

table td.grand {
  border-top: 1px solid #5D6975;;
}

#notices .notice {
  color: #5D6975;
  font-size: 1.2em;
}
.h3 {
  text-align: center;
  line-height: 0.2;
}
footer {
  color: #5D6975;
  width: 100%;
  height: 30px;
  position: absolute;
  bottom: 0;
  border-top: 1px solid #C1CED9;
  padding: 8px 0;
  text-align: center;
}
    </style>
  </head>
  <body style="width: 100%">
    <header class="clearfix">
   <!--    <div id="logo">
        <img src="logo.png">
      </div> -->
      <div class="h3">
    <h3>Al Marsan's Catering Services</h3>
    <h3>41 Magsaysay Street, Parang, Marikina City</h3>
    <h3>Tel: 941-4066 CP: 0916-3777-348 Email: almarsancatering@yahoo.com</h3>
    </div>
      <h1>Sales Report</h1>

      <div class="clearfix">
        <div>Date: {{date('M d, Y')}}</div>
        <div>Generated by: {{ Auth::user()->display_name }}</div>
      </div>
    </header>
    <main>
      <table>
        <thead>
          <tr>
            <th>DATE</th>
            <th>NAME</th>
            <th>EVENT</th>
            <th>FOOD ORDER #</th>
            <th>TOTAL</th>
          </tr>
        </thead>
        <tbody>@php $total = 0 @endphp
          @foreach($event as $eve)
            <tr>
              <td>{{date("m/d/y", strtotime( $eve->event_date.' '.$eve->event_time))}}</td>
              <td>{{$eve->client_fname.' '.$eve->client_lname}}</td>
              <td>{{$eve->event_name}}</td>
              <td> - </td>
              <td>{{number_format($eve->grand_total,2)}}</td>
            </tr>
            @php $total += $eve->grand_total @endphp
          @endforeach
          @foreach($foodorder as $fo)
            <tr>
              <td>{{date("m/d/y", strtotime($fo->food_order_date))}}</td>
              <td>{{$fo->client_fname.' '.$fo->client_lname}}</td>
              <td> - </td>
              <td># {{$fo->food_order_id}}</td>
              <td>{{number_format($fo->total,2)}}</td>
            </tr>
            @php $total += $fo->total @endphp
          @endforeach
          <tr>
            <td class="total" colspan="4">TAX</td>
            <td class="total">{{number_format($total * 0.12,2)}}</td>
          </tr>
          <tr>
            <td colspan="4" class="grand total">OVERALL SALES</td>
            <td class="grand total">{{number_format($total,2)}}</td>
          </tr>
        </tbody>
      </table>
  <!--     <div id="notices">
        <div>NOTICE:</div>
        <div class="notice">A finance charge of 1.5% will be made on unpaid balances after 30 days.</div>
      </div> -->
    </main>
<!--     <footer>
      Invoice was created on a computer and is valid without the signature and seal.
    </footer> -->
  </body>
</html>